Update to tape 3
Because tape 3 uses hasOwnProperty internally we need to restore
it before calling t.equal or things will fall over with:

TypeError: Cannot call method 'call' of undefined